### PR TITLE
show usd

### PR DESCRIPTION
**Pull request by oxSaturn**
20230607goXbXEXG@2x

### CODE REVIEW

**Comment by t0rbik** [comment]
side note: wagmi already exposes tanstack react-query to import useQuery, which is same narrative as swr

**Comment by oxSaturn** [comment]
> side note: wagmi already exposes tanstack react-query to import useQuery, which is same narrative as swr

I see, thanks for heads-up, didn't know that before. Thought swr is smaller than react-query in bundle size, that's why I choose the former when coding.

**Comment by oxSaturn** [comment]
Interesting, cant' find any documentation about `useQuery` on wagmi. Seems it's exported in API, but not documented yet.

**Comment by t0rbik** [comment]
yeh, well you can even export useQuery from `@tanstack-react-query` as it's a dependency of wagmi, same way we can import from zustand.
But i believe there was an issue on their repo to explicitly expose useQuery from wagmi

**Comment by t0rbik** [comment]
@oxSaturn hey. have just read some more ideas on this case. want to underline that this practice of using nested dependency is not safe, bc if package updates it, it can break your code obv

**Comment by oxSaturn** [comment]
> @oxSaturn hey. have just read some more ideas on this case. want to underline that this practice of using nested dependency is not safe, bc if package updates it, it can break your code obv

Mind sharing what you read?

**Comment by t0rbik** [comment]
https://divriots.com/blog/switching-to-pnpm

**Pull request merged**
